function [ assignedLabels ] = generateClassificationTargets (gTruthLabels, assignments,...
                                             positiveIndex, negativeIndex,...
                                             classNames, backgroundClassName)
                                         
    % assignedLabels - numProposalsx1 categorical
    
    for i=1:size(gTruthLabels,1)
        assignedLabels{i} = helper.boxAssignmentUtils.boxLabelsFromAssignment(...
                                        assignments{i}, gTruthLabels{i}, ...
                                        positiveIndex{i}, negativeIndex{i}, ...
                                        classNames, backgroundClassName);
                                    
    end